// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using CoreGraphics;
using Foundation;
using AppKit;
using ObjCRuntime;
using OpenGL;
using OpenTK.Graphics.OpenGL;

namespace MarioKartTrackMaker_macOS
{
	public partial class MyCustomView : NSOpenGLView
	{
		public MyCustomView (IntPtr handle) : base (handle)
		{
		}

        /*public MyCustomView(CGRect rect, NSOpenGLPixelFormat format) : base (rect, format) {
        }*/

        static void DrawTriangle()
        {
            GL.Color3(Color.Red);
            GL.Begin(BeginMode.Triangles);
            GL.Vertex3(0.0, 0.6, 0.0);
            GL.Vertex3(-0.2, -0.3, 0.0);
            GL.Vertex3(0.2, -0.3, 0.0);

            GL.End();
        }

        public override void DrawRect(CGRect dirtyRect)
        {
            OpenGLContext.MakeCurrentContext();

            GL.ClearColor(Color.Brown);

            GL.ClearColor(0, 0, 0, 0);
            GL.Clear(ClearBufferMask.ColorBufferBit);

            //DrawTriangle();

            //MarioKartTrackMaker.ViewerResources.ToolModels.DrawBall(new OpenTK.Vector3(), 5f, 4);
            Console.WriteLine("drawn");
            GL.Flush();
        }

	}
}
