// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MarioKartTrackMaker_macOS3
{
	public partial class ContentViewController : NSViewController
	{
		public ContentViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
