// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MarioKartTrackMaker_macOS
{
	public partial class TestTKWindow : NSWindow
	{
		public TestTKWindow (IntPtr handle) : base (handle)
		{
		}
	}
}
